export const TYPES = {
	Application: Symbol.for('Application'),
	ILogger: Symbol.for('ILogger'),
	IExceptionFilter: Symbol.for('IExceptionFilter'),
	IConfigService: Symbol.for('IConfigService'),
	DatabaseService: Symbol.for('DatabaseService'),
	IMailerService: Symbol.for('IMailerService'),
	IAuthController: Symbol.for('IAuthController'),
	IArticlesController: Symbol.for('IArticlesController'),
	ICategoriesController: Symbol.for('ICategoriesController'),
	IUsersController: Symbol.for('IUsersController'),
	IAuthService: Symbol.for('IAuthService'),
	IArticlesService: Symbol.for('IArticlesService'),
	ICategoriesService: Symbol.for('ICategoriesService'),
	IUsersService: Symbol.for('IUsersService'),
	IArticlesRepository: Symbol.for('IArticlesRepository'),
	ICategoriesRepository: Symbol.for('ICategoriesRepository'),
	IUsersRepository: Symbol.for('IUsersRepository'),
};
